CC=gcc
CFLAG=-g -Wall -Werror -Wextra
BUI=../build

strlen_tests:
	$(CC) $(CFLAG) -D STRLEN s21_string.c s21_string_test.c -o $(BUI)/Quest_1

strcmp_tests:
	$(CC) $(CFLAG) -D STRCMP s21_string.c s21_string_test.c -o $(BUI)/Quest_2

strcpy_tests: 
	$(CC) $(CFLAG) -D STRCPY s21_string.c s21_string_test.c -o $(BUI)/Quest_3

strcat_tests:
	$(CC) $(CFLAG) -D STRCAT s21_string.c s21_string_test.c -o $(BUI)/Quest_4
